project:
  type: book
  output-dir: docs

book:
  title: "Telling Stories with Data"
  subtitle: "With applications primarily in R"
  author: "Rohan Alexander"
  date: "30 March 2023"
  search: true
  cover-image: figures/tellingstorieswithdatapainting.png
  repo-url: https://github.com/RohanAlexander/telling_stories/
  repo-actions: [edit]
  site-url: https://tellingstorieswithdata.com
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters: 
        - 01-introduction.qmd
        - 02-drinking_from_a_fire_hose.qmd
        - 03-workflow.qmd
    - part: "Communication"  
      chapters: 
        - 04-writing_research.qmd
        - 05-static_communication.qmd
    - part: "Acquisition"  
      chapters: 
        - 06-farm.qmd
        - 07-gather.qmd
        - 08-hunt.qmd
    - part: "Preparation"  
      chapters: 
        - 09-clean_and_prepare.qmd
        - 10-store_and_share.qmd
    - part: "Modelling"  
      chapters: 
        - 11-eda.qmd
        - 12-ijalm.qmd
        - 13-ijaglm.qmd
    - part: "Applications"
      chapters: 
        - 14-causality_from_obs.qmd
        - 15-mrp.qmd
        - 16-text.qmd
        - 17-concluding.qmd
  appendices:
    - 20-r_essentials.qmd
    - 21-datasets.qmd
    - 22-rmarkdown.qmd
    - 23-assessment.qmd
    - 24-interactive_communication.qmd
    - 25-datasheet.qmd
    - 26-sql.qmd
    - 27-python.qmd
    - 28-deploy.qmd
    - 29-activities.qmd
    - 98-cocktails.qmd
    - 99-references.qmd
  
bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    callout-appearance: simple
  pdf: 
    documentclass: scrbook
